name: Test action

on:
  push:
  pull_request:

jobs:
  calculate-age:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./
        id: birthday
        with:
          date: '1991-08-17'
      - run: |
          echo "Authors age in years: ${{ steps.birthday.outputs.age }}"
